---
- name: Install Visual Studio Code
  community.general.homebrew_cask:
    name: visual-studio-code
    state: present
  when: ansible_facts['os_family'] == 'Darwin'

- name: Copy VS Code config files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ code_config_path }}"
    mode: "0644"
  with_items:
    - settings.json
    - keybindings.json

- name: List VS Code extensions
  ansible.builtin.command:
    argv:
      - code
      - --list-extensions
  register: code_extensions_list
  changed_when: false
  no_log: true

- name: Install extensions
  ansible.builtin.command:
    argv:
      - code
      - --install-extension
      - "{{ item.id }}"
  register: cmd_output
  changed_when: cmd_output.rc != 0
  with_items: "{{ code_extensions }}"
  when: not item.id in code_extensions_list.stdout_lines
