---
- name: Set init.defaultBranch
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main

- name: Set aliases
  community.general.git_config:
    name: alias.{{ item.alias }}
    scope: global
    value: "{{ item.command }}"
  loop: "{{ git_aliases }}"

- name: Improve pager setting
  community.general.git_config:
    name: core.pager
    scope: global
    value: "less -FX"

- name: Install GPG
  community.general.homebrew:
    name: gnupg
  when: ansible_facts['os_family'] == 'Darwin'
